# This workflow will run tests using node and then publish a package to npmjs.com Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Call Node.js Package

on:
  #workflow_call:
  #release:
  #  types: [created]
  push:

jobs:
  build:
    uses: jamesmortensen/npm-publish-workflow/.github/workflows/npm-publish-workflow@main

